######################################################################
# Automatically generated by qmake (3.1) Mon Jan 24 15:41:00 2022
######################################################################

QT += charts
TEMPLATE = app
TARGET = PharmaCharts
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += barchart.h \
           chart.h \
           compresse.h \
           dataset.h \
           farmaco.h \
           flacone.h \
           formatcombobox.h \
           insertview.h \
           linechart.h \
           maincontent.h \
           mainwindow.h \
           menu.h \
           model.h \
           piechart.h \
           pointchart.h \
           proxymodeladapter.h \
           scatterchart.h \
           tabella.h \
           tablemodeladapter.h \
           valori.h \
           valorinorm.h \
           valoriprezzinorm.h \
           valoriprezzo.h \
           valorivendite.h \
           valorivenditeanno.h \
           valorivenditeitem.h \
           valorivenditenorm.h \
           variabili.h \
           variabilianno.h \
           variabilinome.h \
           variablesdialog.h \
           xmlutil.h
SOURCES += barchart.cpp \
           chart.cpp \
           compresse.cpp \
           dataset.cpp \
           farmaco.cpp \
           flacone.cpp \
           formatcombobox.cpp \
           insertview.cpp \
           linechart.cpp \
           main.cpp \
           maincontent.cpp \
           mainwindow.cpp \
           menu.cpp \
           model.cpp \
           piechart.cpp \
           pointchart.cpp \
           proxymodeladapter.cpp \
           scatterchart.cpp \
           tabella.cpp \
           tablemodeladapter.cpp \
           valori.cpp \
           valorinorm.cpp \
           valoriprezzinorm.cpp \
           valoriprezzo.cpp \
           valorivendite.cpp \
           valorivenditeanno.cpp \
           valorivenditeitem.cpp \
           valorivenditenorm.cpp \
           variabili.cpp \
           variabilianno.cpp \
           variabilinome.cpp \
           variablesdialog.cpp \
           xmlutil.cpp
RESOURCES += images.qrc
